// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMIauyw4NPsg_IKYiupciPlCv0qqGc_ik',
    appId: '1:375526750261:web:1d5e24321e71fecdd7997c',
    messagingSenderId: '375526750261',
    projectId: 'sockettravis-6e629',
    authDomain: 'sockettravis-6e629.firebaseapp.com',
    storageBucket: 'sockettravis-6e629.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWL_qoMfXRnfPaJASPW16cT91qTohH7B4',
    appId: '1:375526750261:android:82793e0d008555d9d7997c',
    messagingSenderId: '375526750261',
    projectId: 'sockettravis-6e629',
    storageBucket: 'sockettravis-6e629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5TN3FRuXnBEDsGHsLjcQ9X3LBgV_5PM8',
    appId: '1:375526750261:ios:4d568861721cea20d7997c',
    messagingSenderId: '375526750261',
    projectId: 'sockettravis-6e629',
    storageBucket: 'sockettravis-6e629.firebasestorage.app',
    iosBundleId: 'com.example.examenFlutterU2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5TN3FRuXnBEDsGHsLjcQ9X3LBgV_5PM8',
    appId: '1:375526750261:ios:4d568861721cea20d7997c',
    messagingSenderId: '375526750261',
    projectId: 'sockettravis-6e629',
    storageBucket: 'sockettravis-6e629.firebasestorage.app',
    iosBundleId: 'com.example.examenFlutterU2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMIauyw4NPsg_IKYiupciPlCv0qqGc_ik',
    appId: '1:375526750261:web:ef5f4152e4813474d7997c',
    messagingSenderId: '375526750261',
    projectId: 'sockettravis-6e629',
    authDomain: 'sockettravis-6e629.firebaseapp.com',
    storageBucket: 'sockettravis-6e629.firebasestorage.app',
  );

}